// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListMVC.Data;

namespace ToDoListMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoListMVC.Models.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 746, DateTimeKind.Local).AddTicks(7203),
                            Description = "Add database with entity framework",
                            Done = false,
                            Title = "DB"
                        },
                        new
                        {
                            ID = 2,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 747, DateTimeKind.Local).AddTicks(7596),
                            Description = "Add messages on index page to inform about actions (create/edit/delete)",
                            Done = true,
                            Title = "Messages"
                        },
                        new
                        {
                            ID = 3,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 747, DateTimeKind.Local).AddTicks(8059),
                            Description = "Crossout deadline when expired",
                            Done = false,
                            Title = "Deadline"
                        },
                        new
                        {
                            ID = 4,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 747, DateTimeKind.Local).AddTicks(8077),
                            Description = "Do not show controls on the delete page",
                            Done = false,
                            Title = "Controls"
                        },
                        new
                        {
                            ID = 5,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 747, DateTimeKind.Local).AddTicks(8090),
                            Description = "Two containers with completed and not completed todos",
                            Done = false,
                            Title = "Filter"
                        },
                        new
                        {
                            ID = 6,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 747, DateTimeKind.Local).AddTicks(8114),
                            Description = "Model validation on edit/create page",
                            Done = false,
                            Title = "Validation"
                        },
                        new
                        {
                            ID = 7,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 747, DateTimeKind.Local).AddTicks(8127),
                            Description = "Add information page, describe why this project was created",
                            Done = false,
                            Title = "Information"
                        },
                        new
                        {
                            ID = 8,
                            Deadline = new DateTime(2021, 4, 28, 23, 25, 50, 747, DateTimeKind.Local).AddTicks(8139),
                            Description = "Scrolling is not working (not showing) when there are more than 9 items",
                            Done = false,
                            Title = "Scrolling"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
